PLOT_FIGURE_SIZE = [6, 5]
PLOT_FIGURE_DPI = 280
PLOT_SAMPLES = 256

PLOT_LABEL_FONT_SIZE = 18
PLOT_TITLE_FONT_SIZE = 22
PLOT_LAGRANGE_COLOR = (0, 0.75, 1)
PLOT_POLY_COLOR = (0, 0, 0)

MARKER_COLOR = (1, 0, 0)
MARKER_SIZE = 8
MARKER_STYLE = 'h'
